//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLMS.Transfer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.weblms.ru", ConfigurationName="Transfer.ITransfer")]
    public interface ITransfer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.weblms.ru/ITransfer/TestConnection", ReplyAction="http://service.weblms.ru/ITransfer/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.weblms.ru/ITransfer/TestConnection", ReplyAction="http://service.weblms.ru/ITransfer/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadRequest) of message DownloadRequest does not match the default value (DownloadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://service.weblms.ru/ITransfer/DownloadFile", ReplyAction="http://service.weblms.ru/ITransfer/DownloadFileResponse")]
        WebLMS.Transfer.RemoteFileInfo DownloadFile(WebLMS.Transfer.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.weblms.ru/ITransfer/DownloadFile", ReplyAction="http://service.weblms.ru/ITransfer/DownloadFileResponse")]
        System.Threading.Tasks.Task<WebLMS.Transfer.RemoteFileInfo> DownloadFileAsync(WebLMS.Transfer.DownloadRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UploadFileInfo) of message UploadFileInfo does not match the default value (ConvertFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://service.weblms.ru/ITransfer/ConvertFile", ReplyAction="http://service.weblms.ru/ITransfer/ConvertFileResponse")]
        WebLMS.Transfer.ResponseFileInfo ConvertFile(WebLMS.Transfer.UploadFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.weblms.ru/ITransfer/ConvertFile", ReplyAction="http://service.weblms.ru/ITransfer/ConvertFileResponse")]
        System.Threading.Tasks.Task<WebLMS.Transfer.ResponseFileInfo> ConvertFileAsync(WebLMS.Transfer.UploadFileInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://service.weblms.ru", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.weblms.ru", Order=0)]
        public string FileName;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string FileName) {
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://service.weblms.ru", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.weblms.ru")]
        public string Email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.weblms.ru")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.weblms.ru")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.weblms.ru", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string Email, string FileName, long Length, System.IO.Stream FileByteStream) {
            this.Email = Email;
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileInfo", WrapperNamespace="http://service.weblms.ru", IsWrapped=true)]
    public partial class UploadFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.weblms.ru")]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.weblms.ru", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public UploadFileInfo() {
        }
        
        public UploadFileInfo(string Email, System.IO.Stream FileByteStream) {
            this.Email = Email;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResponseFileInfo", WrapperNamespace="http://service.weblms.ru", IsWrapped=true)]
    public partial class ResponseFileInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.weblms.ru", Order=0)]
        public string Path;
        
        public ResponseFileInfo() {
        }
        
        public ResponseFileInfo(string Path) {
            this.Path = Path;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransferChannel : WebLMS.Transfer.ITransfer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransferClient : System.ServiceModel.ClientBase<WebLMS.Transfer.ITransfer>, WebLMS.Transfer.ITransfer {
        
        public TransferClient() {
        }
        
        public TransferClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransferClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLMS.Transfer.RemoteFileInfo WebLMS.Transfer.ITransfer.DownloadFile(WebLMS.Transfer.DownloadRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public string DownloadFile(ref string FileName, out long Length, out System.IO.Stream FileByteStream) {
            WebLMS.Transfer.DownloadRequest inValue = new WebLMS.Transfer.DownloadRequest();
            inValue.FileName = FileName;
            WebLMS.Transfer.RemoteFileInfo retVal = ((WebLMS.Transfer.ITransfer)(this)).DownloadFile(inValue);
            FileName = retVal.FileName;
            Length = retVal.Length;
            FileByteStream = retVal.FileByteStream;
            return retVal.Email;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebLMS.Transfer.RemoteFileInfo> WebLMS.Transfer.ITransfer.DownloadFileAsync(WebLMS.Transfer.DownloadRequest request) {
            return base.Channel.DownloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebLMS.Transfer.RemoteFileInfo> DownloadFileAsync(string FileName) {
            WebLMS.Transfer.DownloadRequest inValue = new WebLMS.Transfer.DownloadRequest();
            inValue.FileName = FileName;
            return ((WebLMS.Transfer.ITransfer)(this)).DownloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLMS.Transfer.ResponseFileInfo WebLMS.Transfer.ITransfer.ConvertFile(WebLMS.Transfer.UploadFileInfo request) {
            return base.Channel.ConvertFile(request);
        }
        
        public string ConvertFile(string Email, System.IO.Stream FileByteStream) {
            WebLMS.Transfer.UploadFileInfo inValue = new WebLMS.Transfer.UploadFileInfo();
            inValue.Email = Email;
            inValue.FileByteStream = FileByteStream;
            WebLMS.Transfer.ResponseFileInfo retVal = ((WebLMS.Transfer.ITransfer)(this)).ConvertFile(inValue);
            return retVal.Path;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebLMS.Transfer.ResponseFileInfo> WebLMS.Transfer.ITransfer.ConvertFileAsync(WebLMS.Transfer.UploadFileInfo request) {
            return base.Channel.ConvertFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebLMS.Transfer.ResponseFileInfo> ConvertFileAsync(string Email, System.IO.Stream FileByteStream) {
            WebLMS.Transfer.UploadFileInfo inValue = new WebLMS.Transfer.UploadFileInfo();
            inValue.Email = Email;
            inValue.FileByteStream = FileByteStream;
            return ((WebLMS.Transfer.ITransfer)(this)).ConvertFileAsync(inValue);
        }
    }
}
